version: '3.9'

services:
  web:
    build: .
    command: >
      bash -c "
      python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/univ
    ports:
      - "8000:8000"
    env_file:
      - .env
